//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ID { get; set; }
        public string ItemID { get; set; }
        public string CartID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
