//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInfo
    {
        public int ID { get; set; }
        public string InfoContact { get; set; }
        public string Warranty { get; set; }
        public string Showroom { get; set; }
    }
}
